server:
  port: 9091
  
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      
kafka:
  emailtopic:
    name: email
    partitions: 3
    replications: 1
  smstopic:
    name: sms
    partitions: 3
    replications: 1
  whatsapptopic:
    name: whatsapp
    partitions: 3
    replications: 1    
  